### ISSUE TITLE
How Do You Learn?

### ISSUE THREAD

**Issue by braidn** [raganwald/AMA#2]
Of course this is a super open ended question but, that is kind of the point. How have these methods morphed and changed over the years and perhaps do you always look at yourself as an apprentice (as in how [Hoover/Oshineye](http://www.amazon.com/Apprenticeship-Patterns-Guidance-Aspiring-Craftsman/dp/0596518382) describes it) or perhaps something else? 

Thanks again for doing this!

**Comment by raganwald** [comment]
I was a voracious reader of full-length when I was younger. Not so much now, and I can see that my learning has slowed as my reading of full-length books has slowed.
