### ISSUE TITLE
What aspects of your life have been most influential on your career?

### ISSUE THREAD

**Issue by mxriverlynn** [raganwald/AMA#4]
I love hearing about people's life experiences and how it shapes the way they think about software development and technology. In my experience, the best developers typically have a mastery of something other than software / technology, in addition to software / technology (though, not always).

What aspects of your life have been most influential on your career, and the way you approach software development?

**Comment by raganwald** [comment]
My mother: [A Woman’s Story](http://braythwayt.com/posterous/2012/03/29/a-womans-story.html)

And the middle period of my working life, when I sold Macintosh computers at a time when they were (to my mind) demonstrably superior, yet unpopular.
