### ISSUE TITLE
Do you remember sending this email?

### ISSUE THREAD

**Issue by r00k** [raganwald/AMA#6]
![screen shot 2015-03-15 at 12 31 01 am](https://cloud.githubusercontent.com/assets/46677/6654162/97caae98-caaa-11e4-9414-cb7012768a7a.png)

As a brand-new blog author, it pretty much made my week. :)

**Comment by baweaver** [comment]
Spread the love to other authors, as you know it helps a lot. Really both of you are heroes to me in terms of programming.

**Comment by raganwald** [comment]
I do, glad you followed your :heart:
