### ISSUE TITLE
How do you make open-source decisions?

### ISSUE THREAD

**Issue by davidtheclark** [raganwald/AMA#7]
(I guess if you want to write about making decisions _in general_, I'd be interested to read about that, too.)

I don't think I've read enough about how people make solid decisions in this area. Some specific example questions (sort of redundant, but the idea is just to flesh out the subject I'm interested in hearing about):
- How to choose which open-source alternative to depend on? (— and I don't mean "Which JS frameworks do you prefer?" but rather "Given a few options to solve some particular problem, how do you decide which one to go with?")
- How to decide whether a project is "well-maintained" enough to depend on? (— activity, issue count, response time, code quality by your own standards, etc.)
- When is it best to write your own thing instead of trusting anyone else to do the work for you?
- Does corporate support for a project matter, one way or the other?

You know, stuff like that. I'd like to read anything you want to write about the subject.

**Comment by raganwald** [comment]
There are two mes, the one at work and the one at home. The me at work makes very boring decisions about open source and technology in general. Did you know that I’ve spent many years writing Java for Big Iron?

The me at home selfishly looks for things that are pleasant to read about and communities that seem welcoming. Paul Graham organized a conference where I heard Matz speak for the first time, and I swicthed from learning Groovy to learning Ruby on the spot.
